services:
  pdfcompress:
    container_name: pdfcompress
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - pdf_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - APP_ENV=production
    restart: unless-stopped

volumes:
  pdf_data:
    name: pdf_data

